[2020-04-26 18:41:20,008][ERROR][logg.main:127] Error connect to Mysql   ()
Traceback (most recent call last):
  File "hash_1.py", line 123, in main
    con.registration_user()
  File "hash_1.py", line 87, in registration_user
    storage = salt + dk
NameError: name 'salt' is not defined
